StudentApp.Web/Controllers/CourseController.cs
using Azure;
using CourseApp.Manager.Course;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentApp.Object.DTOs.Course;
using StudentApp.Object.Pagination;

namespace CourseApp.Web.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private readonly ICourseManager _courseManager;

        public CourseController(ICourseManager courseManager)
        {
            _courseManager = courseManager;
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCourseDto input)
        {
            await _courseManager.Create(input);
            return RedirectToAction("List");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            return View(await _courseManager.Get(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditCourseDto input)
        {
            await _courseManager.Update(input);
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _courseManager.Delete(id);
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> List(int page = 1)
        {
            var courses = await _courseManager.Get();
            if (page < 1) page = 1;
            var pager = courses.Paginate<CourseDto>(courses.Count, page, 10);
            ViewBag.Pager = pager;
            return View();
        }
        public async Task<PartialViewResult> SearchCourses(int page = 1, string searchtxt = "")
        {
            var courses = await _courseManager.Get();
            searchtxt = searchtxt?.ToLower();
            if (page < 1) page = 1;
            var pager = courses.Paginate<CourseDto>(courses.Count, page, 10);
            ViewBag.Pager = pager;
            var result = !string.IsNullOrEmpty(searchtxt) ? pager.Items.Where(x => x.Name.ToLower().Contains(searchtxt) ||
            x.Author.ToLower().Contains(searchtxt)
            ).ToList() : pager.Items;

            return PartialView("_GridView", result);
        }
    }
}

StudentApp.Web/Controllers/ExamController.cs
using CourseApp.Manager.Course;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudentApp.Manager.Exam;
using StudentApp.Manager.Student;
using StudentApp.Object.DTOs.Exam;

namespace StudentApp.Web.Controllers
{
    public class ExamController : Controller
    {
        private readonly IExamManager _examManager;
        private readonly ICourseManager _courseManager;
        private readonly IStudentManager _studentManager;

        public ExamController(IExamManager examManager, ICourseManager courseManager, IStudentManager studentManager)
        {
            _examManager = examManager;
            _courseManager = courseManager;
            _studentManager = studentManager;
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new CreateExamDto();
            var courses = await _courseManager.Get();
            model.CourseList = courses.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateExamDto input)
        {
            await _examManager.Create(input);
            return RedirectToAction("List");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _examManager.Get(id);
            var courses = await _courseManager.Get();
            model.CourseList = courses.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditExamDto input)
        {
            await _examManager.Update(input);
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _examManager.Delete(id);
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            return View(await _examManager.Get());
        }
        public async Task<PartialViewResult> SearchExams(string searchtxt)
        {
            var exams = await _examManager.Get();
            searchtxt = searchtxt?.ToLower();
            var result = !string.IsNullOrEmpty(searchtxt) ? exams.Where(x => x.CourseName.ToLower().Contains(searchtxt) ||
            x.ExamDate.ToString().ToLower().Contains(searchtxt)
            ).ToList() : exams;

            return PartialView("_GridView", result);
        }

        [HttpGet]
        public async Task<IActionResult> StudentMarksRecord()
        {
            return View(await _examManager.GetStudentMarksRecord());
        }
        [HttpGet]
        public async Task<IActionResult> CreateStudentMarks()
        {
            var model = new CreateStudentMarksDto();
            var students = await _studentManager.Get();
            var exams = await _examManager.Get();
            model.StudentList = students.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();
            model.ExamList = exams.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.CourseName }).ToList();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> CreateStudentMarks(CreateStudentMarksDto input)
        {
            await _examManager.CreateStudentMarks(input);
            return RedirectToAction("StudentMarksRecord");
        }
        [HttpGet]
        public async Task<IActionResult> DeleteMarks(int id)
        {
            await _examManager.DeleteMarks(id);
            return RedirectToAction("StudentMarksRecord");
        }

    }
}

StudentApp.Web/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using StudentApp.Manager.Student;
using StudentApp.Object.DTOs.Course;
using StudentApp.Object.DTOs.Student;
using StudentApp.Object.Pagination;

namespace StudentApp.Web.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private readonly IStudentManager _studentManager;

        public StudentController(IStudentManager studentManager)
        {
            _studentManager = studentManager;
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateStudentDto input)
        {
            await _studentManager.Create(input);
            return RedirectToAction("List");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            return View(await _studentManager.Get(id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditStudentDto input)
        {
            await _studentManager.Update(input);
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _studentManager.Delete(id);
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> List(int page = 1)
        {
            Log.Information("Calling StudentController > List ...");

            var students = await _studentManager.Get();
            if (page < 1) page = 1;
            var pager = students.Paginate<StudentDto>(students.Count, page, 10);
            ViewBag.Pager = pager;
            return View();
        }

        public async Task<PartialViewResult> SearchStudents(int page = 1, string searchtxt = "")
        {
            var students = await _studentManager.Get();
            searchtxt = searchtxt?.ToLower();
            if (page < 1) page = 1;
            var pager = students.Paginate<StudentDto>(students.Count, page, 10);
            ViewBag.Pager = pager;
            var result = !string.IsNullOrEmpty(searchtxt) ? pager.Items.Where(x => x.Name.ToLower().Contains(searchtxt) ||
            x.RollNumber.ToLower().Contains(searchtxt) ||
            x.Email.ToLower().Contains(searchtxt) ||
            x.Phone.ToLower().Contains(searchtxt) ||
            x.Address.ToLower().Contains(searchtxt) ||
            x.City.ToLower().Contains(searchtxt) ||
            x.State.ToLower().Contains(searchtxt)
            ).ToList() : pager.Items;

            return PartialView("_GridView", result);
        }

        [HttpGet]
        public async Task<IActionResult> MarksSheet(int studentId)
        {
            var markSheet = await _studentManager.GetStudentMarksSheet(studentId);
            return View(markSheet);
        }
    }
}

StudentApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentApp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentApp.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentApp.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="List">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="List">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exam" asp-action="List">Exams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exam" asp-action="StudentMarksRecord">Record Student Marks</a>
                        </li>
                    </ul>
                </div>
               
                <div class="d-flex bd-highlight">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                        <ul class="navbar-nav flex-grow-1">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StudentApp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>